<?php

$title='I am the title';
$programName='RandomName';
$programExplanation='Random Explanation';
$dbObject = new mysqli("localhost","web","nouser","bible");
$mobile=0;

//Functions
function optgroups($dbObject) {


    // Select Statement Section
    $sqlSectionSelect="SELECT bsect as sectionLetter, sectname as sectionName FROM section ORDER BY sectorder;";

    // sql Object Section
    if (!( $sqlSectionObject=$dbObject->prepare($sqlSectionSelect) )) {
        print "Prepare section failed: (" . $dbObject->errno . ")" . $dbObject->error;
    }

    //Execute Sections

    if (!($sqlSectionObject->execute())) {
        print "Execute section failed: (" . $dbObject->errno . ") " . $dbObject->error;
    }

    // create and initialize variables for results Section
    $sectionLetter = NULL;
    $sectionName = NULL;
    $section = array("ALL"=>"Entire Collection"); // hard code ALL

    // bind variables for results Section
    if (!( $sqlSectionObject->bind_result($sectionLetter,$sectionName))) {
        print "bind_param section failed: (" . $dbObject->errno . ")" . $dbObject->error;
        }

    // fetch records for Section

    while ($sqlSectionObject->fetch()) {
        //Store in Array for later use
        $section["$sectionLetter"] = "$sectionName";
    }

    //Select Statement Books
    $sqlBookSelect="SELECT bnum, bname FROM books WHERE bsect = ? ORDER BY bnum;";

    // sql Object Books
    if (!( $sqlBookObject=$dbObject->prepare($sqlBookSelect))) {
        print "Prepare book failed: (" . $dbObject->errno . ")" . $dbObject->error;
    }

    foreach ( $section as $bsect=>$sectname ) {

        //setup optgroup
        print "\t<optgroup label=\"$sectname\">\n";

        // hardcode for "ALL"
        if ( $bsect == "ALL" ) {
            foreach ( $section as $bsect=>$sectname ) {
                print "\t<option value=\"$bsect\">$sectname</option>";
            }
        }
        else {
            // bind Param for Books Execute
            if (!($sqlBookObject->bind_param("s", $bsect))) {
                print "bind_param books failed: (" . $dbObject->errno .")" . $dbObject->error;
            }

            // execute Books
            if (!($sqlBookObject->execute())) {
                print "Execute books failed: (" . $dbObject->errno . ")" . $dbObject->error;
            }

            // create and initialize variables to use for results
            $bnum = NULL;
            $bname = NULL;

            // bind results to variables
            if (!($sqlBookObject->bind_result($bnum, $bname))) {
                print "bind_results books failed: (" . $dbObject->errno . ")" . $dbObject-error;
            }

            // fetch books in loop
            while ($sqlBookObject->fetch()) {
                print "\t\t<option value=\"$bnum\">$bname</option>\n";
            }
        }

        //end optgroup
        print "\t</optgroup>\n";
    }
    $dbObject->close();
}


//mobile view
if ($mobile) {

//close php and print out html with jQueryMobile
?>

<!doctype html>
<html>
<head>
    <title>Form Elements</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="http://code.jquery.com/mobile/latest/jquery.mobile.min.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js "></script>
    <script type="text/javascript" src="http://code.jquery.com/mobile/latest/jquery.mobile.min.js"></script>
</head>
<body>
	<section data-role="page" id="first" data-theme="c">
		<header data-role="header">
			<h1>Forms</h1>
		</header>
		<article data-role="content">
			<h2>Mobile Application</h2>
			<form method="get" action="dhtml/9.Forms.dhtml">
				<input name="subject" type="hidden" value="Class" />
                
				<fieldset>
					<legend>Where to search</legend>
					<label for="books">Books</label>
					<select tabindex="-1" multiple="multiple" name="book" id="book" data-native-menu="false">
		            
                    <?php optgroups($dbObject) ?>
                    
                    </select>
					<br />
					<label for="search">Search Words:</label>
					<input type="text" name="search" id="search" />
					<br />
				</fieldset>
				<div>
					<input type="submit" name="submit" value="Send Form" />
				</div>
			</form>
		</article>
	<footer data-role="footer"><h1>int620 - jQuery Mobile View</h1></footer>
	</section>
</body>
</html>

<?php } // Close php if

else {

?>

<!doctype html>
<html>
<head>
    <title>Form Elements</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="http://code.jquery.com/mobile/latest/jquery.mobile.min.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js "></script>
    <script type="text/javascript" src="http://code.jquery.com/mobile/latest/jquery.mobile.min.js"></script>
</head>
<body>
	<section data-role="page" id="first" data-theme="a">
		<header data-role="header">
			<h1>Forms</h1>
		</header>
		<article data-role="content">
			<h2>Desktop Application</h2>
			<form method="get" action="dhtml/9.Forms.dhtml">
				<input name="subject" type="hidden" value="Class" />
                
				<fieldset>
					<legend>Where to Search</legend>
					<label for="book">Books</label>
					<select id="book" name="book">
		            
                    <?php optgroups($dbObject) ?>
                    
                    </select>
					<br />
					<label for="studentid">Word or Words to search</label>
					<input type="text" name="book" id="studentid" />
					<br />
				</fieldset>
				<div>
					<input type="submit" name="submit" value="Send Form" />
				</div>
			</form>
		</article>
	<footer data-role="footer"><h1>int620 - jQuery Desktop View</h1></footer>
	</section>
</body>
</html>
<?php } // Close else ?>
