<?php

$title='I am the title';
$programName='RandomName';
$programExplanation='Random Explanation';

?>


<!DOCTYPE html
	PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US" xml:lang="en-US">

<head>

    <title><?=$title?></title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

</head>

<body bgcolor="white">
<?php 
    
?>
<p><strong><?=$programName ?></strong></p>
<p><?=$programExplanation ?></p>

<form method="post" action="">

<table>
<tr>
    <td>What to search:</td>
    
    <td>
    <select name="book"  id="book">

    <?php

    // dbObject
    $dbObject = new mysqli("localhost","web","nouser","bible");

    // Select Statement Section
    $sqlSectionSelect="SELECT bsect as sectionLetter, sectname as sectionName FROM section ORDER BY sectorder;";

    // sql Object Section
    if (!( $sqlSectionObject=$dbObject->prepare($sqlSectionSelect))) {
        print "Prepare section failed: (" . $dbObject->errno . ")" . $dbObject->error;
    }
    
    //Execute Sections

    if (!($sqlSectionObject->execute())) {
        print "Execute section failed: (" . $dbObject->errno . ") " . $dbObject->error;
    }

    // create and initialize variables for results Section
    $sectionLetter = NULL;
    $sectionName = NULL;
    $section = array("ALL"=>"Entire Collection"); // hard code ALL

    // bind variables for results Section
    if (!( $sqlSectionObject->bind_result($sectionLetter,$sectionName))) {
        print "bind_param section failed: (" . $dbObject->errno . ")" . $dbObject->error;
        }
   
    // fetch records for Section

    while ($sqlSectionObject->fetch()) {
        //Store in Array for later use
        $section["$sectionLetter"] = "$sectionName";
    }

    //Select Statement Books
    $sqlBookSelect="SELECT bnum, bname FROM books WHERE bsect = ? ORDER BY bnum;";

    // sql Object Books
    if (!( $sqlBookObject=$dbObject->prepare($sqlBookSelect))) {
        print "Prepare book failed: (" . $dbObject->errno . ")" . $dbObject->error;    
    }

    foreach ( $section as $bsect=>$sectname ) {
        
        //setup optgroup
        print "\t<optgroup label=\"$sectname\">\n";
        
        // hardcode for "ALL"
        if ( $bsect == "ALL" ) {
            foreach ( $section as $bsect=>$sectname ) {
                print "\t<option value=\"$bsect\">$sectname</option>";
            }
        }
        else {
            // bind Param for Books Execute
            if (!($sqlBookObject->bind_param("s", $bsect))) {
                print "bind_param books failed: (" . $dbObject->errno .")" . $dbObject->error;
            }
    
            // execute Books
            if (!($sqlBookObject->execute())) {
                print "Execute books failed: (" . $dbObject->errno . ")" . $dbObject->error;
            }
    
            // create and initialize variables to use for results
            $bnum = NULL;
            $bname = NULL;
    
            // bind results to variables
            if (!($sqlBookObject->bind_result($bnum, $bname))) {
                print "bind_results books failed: (" . $dbObject->errno . ")" . $dbObject-error;
            }
    
            // fetch books in loop
            while ($sqlBookObject->fetch()) {
                print "\t\t<option value=\"$bnum\">$bname</option>\n";
            }
        }

        //end optgroup
        print "\t</optgroup>\n";
    }
    $dbObject->close();

    ?>
    
    </select>
    </td>
</tr> 


<tr>
    <td>Word or words to search for:</td> <td><input type="text" name="phrase"  size="60" /></td>
</tr>


<tr>
    <td>Treat words as phrase:</td> <td><label><input type="radio" name="as_phrase" value="1" />yes</label> <label><input type="radio" name="as_phrase" value="0" checked="checked" />no</label></td>
</tr>


<tr>
    <td>Return count only:</td> <td><label><input type="radio" name="count_only" value="1" />yes</label> <label><input type="radio" name="count_only" value="0" checked="checked" />no</label></td>
</tr>

</table>

<br /><input type="submit" name="choice" value="Search" /><div><input type="hidden" name=".cgifields" value="count_only"  /><input type="hidden" name=".cgifields" value="as_phrase"  />

</div>

</form>

<br />
<?php
    $visitTime=date('Y-m-d H:i:s', $_SERVER['REQUEST_TIME']);
    $browserVersion=$_SERVER['HTTP_USER_AGENT'];
    $visitorIP=$_SERVER['REMOTE_ADDR'];
    print "You requested this page with $browserVersion from $visitorIP at $visitTime";
?>       

</body>
</html>
